name: circle_indicator
description: Small library that builds a circle indicator for the PageViewer that can be used on Android and iOS apps.
version: 0.0.4
homepage: https://www.long1.eu
author: long1eu <home@long1.eu>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0

